### PR TITLE
payload should also be responded by bot

### PR DESCRIPTION
**Pull request by Calvin-Lin**

### CODE REVIEW

**Comment by tw0517tw** [comment]
Is this necessary?

**Comment by Calvin-Lin** [comment]
Yes. When bot receive a postback, isMessage will be false. So, isPayload should be checked in case that is a postback event.

**Comment by tw0517tw** [comment]
I'm not sure if we need this assumption that this **example bot** will receive postback events. The example should focus on the purpose of this package, which is handling handovers, not on the bot logic detail of how to handle postback events or any other event types.

**Comment by Calvin-Lin** [comment]
I think it should either be
```
if (!context.event.isStandby) {
    await context.sendText('Respond by bot.');
}
```
or
```
if (!context.event.isStandby && (context.event.isMessage || context.event.isPayload)) {
    await context.sendText('Respond by bot.');
}
```
The original example is misleading.

**Comment by chentsulin** [comment]
I prefer this one:
```js
if (!context.event.isStandby) {
  await context.sendText('Respond by bot.');
}
```

**Review by chentsulin — APPROVED** [review]

**Pull request merged**
